export const translations = {
    'zh-TW': {
        // static HTML items
        'menu_file': '檔案',
        'menu_new': '新建',
        'menu_project_manager': '專案總管',
        'menu_load_folder': '讀取資料夾',
        'menu_load_zip': '讀取壓縮檔',
        'menu_download': '下載',
        'menu_add_music': '加入音樂',
        'menu_add_video': '加入影片',
        'menu_import_from_video': '從影片匯入',
        'menu_read_maidata': '讀取maidata',
        'menu_edit': '編輯',
        'menu_undo': '復原',
        'menu_redo': '重作',
        'menu_rotate_cw': '順時針旋轉',
        'menu_rotate_ccw': '逆時針旋轉',
        'menu_rotate_180': '180度旋轉',
        'menu_flip_v': '上下反轉',
        'menu_flip_h': '左右反轉',
        'menu_tools': '功能/工具',
        'menu_cursor_to_playhead': '游標移至播放頭',
        'menu_playhead_to_cursor': '播放頭移至游標',
        'menu_record_video': '錄製影片',
        'menu_edit_music': '編輯音樂開頭',
        'menu_tap_bpm': 'Tap BPM',
        'menu_quick_generate': '快速生成',
        'menu_fetch_mainote': '從Mainote抓取資料',
        'menu_preview_popup': '預覽彈出',
        'menu_resources': '資源管理',
        'menu_chart_info': '譜面資訊',
        'menu_settings': '設定',
        'ui_offset': '偏移 ',
        'ui_difficulty': '難度切換 ',
        'ui_playback_speed': '播放速度 ',
        'ui_display_mode': '顯示模式 ',
        'ui_mode_simai': 'simai 語法',
        'ui_mode_visual': '軌道',
        'ui_ready_beat': '預備拍',
        'editor_placeholder': '在此輸入譜面資料...',

        // settings configuration keys
        'settings_title': '設定',
        'settings_cat_basic': '基本',
        'settings_cat_display': '顯示',
        'settings_cat_sound': '音效',
        'settings_cat_other': '其他',
        'settings_speed': ' Tap/Hold 速度',
        'settings_slide_speed': ' Slide 速度',
        'settings_touch_speed': ' Touch 速度',
        'settings_middle_display': '中間顯示',
        'settings_middle_display_off': '關閉',
        'settings_middle_display_combo': 'COMBO',
        'settings_middle_display_score': '分數',
        'settings_brightness': '背景暗度',
        'settings_pink_stars': '粉紅色星星',
        'settings_show_sensor': '顯示感應器',
        'settings_show_sensor_text': '暫停時顯示感應器文字',
        'settings_hide_bg_paused': '暫停時隱藏背景',
        'settings_rotate_stars': '星星旋轉',
        'settings_vol_global': '全局音量',
        'settings_vol_music': '音樂音量',
        'settings_vol_sfx': '音效音量',
        'settings_vol_individual': '個別音效音量',
        'settings_no_hold_end_sfx': '不播放 Hold 結尾音效',
        'settings_autocomplete': '編輯器自動補齊括號',
        'settings_max_slides': '螢幕上最大滑星顯示數量',
        'settings_debounce_time': '編輯器刷新時間 (ms)',
        'settings_show_fps': '顯示FPS介面',
        'settings_auto_pause': '滾動時自動暫停',
        'settings_global_timeline': '顯示全域時間軸',
        'settings_language': '語言 / Language',
        'settings_btn_save': '儲存',
        'settings_btn_apply': '套用',
        'settings_btn_cancel': '取消',
        'settings_btn_reset': '重置數值',

        // SFX names
        'sfx_clock': '預備拍 / Metronome',
        'sfx_answer': '滑條判定 / Slide Trigger',
        'sfx_judge': '點擊音 / Tap',
        'sfx_judge_ex': 'EX 點擊音 / EX Tap',
        'sfx_judge_break': '點擊 Break / Break Tap',
        'sfx_judge_break_slide': '滑條 Break / Break Slide',
        'sfx_break': '判定 Break / Break Hit',
        'sfx_slide': '滑動音 / Slide Touch',
        'sfx_break_slide_start': 'Break 滑條起點',
        'sfx_touch': '觸控音 / Touch Hit',
        'sfx_hanabi': '煙火判定音 / Hanabi Touch',

        // Dynamic toasts & Popups
        'toast_saved': '已儲存！',
        'toast_undo': '復原譜面變更',
        'toast_redo': '重作譜面變更',
        'toast_import_video_success': '已從影片匯入背景影片與音樂',
        'toast_save_video_success': '已儲存背景影片',
        'toast_save_video_failed': '儲存背景影片失敗',
        'toast_invalid_number': '請確保所有輸入都是有效的數字',
        'toast_bpm_set': '已設定 BPM：',
        'toast_speed_set': '已設定播放速度：',
        'popup_record_title': '影片錄製',
        'record_range': '錄製範圍: {start}s - {end}s (共 {duration}s)',
        'record_resolution': '解析度:',
        'record_custom': '自訂...',
        'record_custom_w': '自訂寬度:',
        'record_custom_h': '自訂高度:',
        'record_custom_fps': '自訂 FPS 幀率:',
        'record_bgm_vol': 'BGM 音量:',
        'record_sfx_vol': 'SFX 音量:',
        'record_include_audio': '包含音訊:',
        'record_include_sfx': '包含打擊音效:',
        'btn_start': '開始',
        'popup_help_title': '幫助說明',
        'btn_ok': '確定',
        'btn_close': '關閉',
        'btn_reset': '重置',

        // Newly added dynamic strings
        'toast_import_music_first': '請先匯入音樂',
        'toast_audio_cropped': '音訊已自播放頭裁剪',
        'toast_audio_padded': '已在音訊開頭補白',
        'toast_padded_seconds': '已補白 {seconds}s。',
        'toast_crop_too_long': '裁剪長度超過總長。',
        'toast_audio_restored': '已還原至最原始音訊狀態',
        'toast_tap_bpm_min': '請先敲擊至少 2 次 Tap 再保存 BPM。',
        'toast_bpm_failed': 'BPM 計算失敗，請重新敲擊。',
        'toast_supabase_missing': 'Supabase 未載入，請在 index.html 加入 CDN：<script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"></script>',
        'toast_charts_found': '找到 {count} 個譜面',
        'toast_error': '錯誤：{message}',
        'toast_no_matching_charts': '未找到符合條件的譜面',
        'toast_loaded_song': '已載入：{title}',
        'toast_new_project_created': '已建立新專案',
        'toast_parse_failed': '解析譜面失敗，請檢查格式是否正確',
        'toast_invalid_playback_speed': '請輸入有效的播放速度',
        'toast_speed_reset': '重置播放速度',
        'toast_no_audio_file': '找不到音訊檔案',
        'toast_read_tags_success': '成功讀取標籤：{title}',
        'no_title': '無標題',
        'toast_parsed_from_filename': '已從檔名解析資訊',
        'toast_opened_new_project': '已開啟為新專案',
        'toast_loaded_to_current_project': '已載入至目前專案',
        'toast_mediabunny_missing': 'Mediabunny 未載入，無法錄製',
        'toast_switched_to_project': '已切換至專案：{name}',
        'unnamed_project': '未命名專案',
        'toast_deleted_project': '已刪除專案',
        'toast_end_time_error': '結束時間需大於開始時間',
        'toast_render_complete': '逐幀渲染完成，檔案已下載',
        'toast_render_failed': '渲染失敗：',
        'toast_start_rendering': '開始逐幀渲染：{count} 幀',

        'resource_idb_storage_status': 'IndexedDB 儲存狀態：',
        'resource_total_usage': '總計使用量',
        'btn_clear_cache': '清除緩存',
        'popup_clear_cache_title': '清除緩存',
        'btn_clear_all_data': '清除所有資料',
        'btn_clear_chart_cache': '清除譜面暫存',
        'btn_clear_assets_cache': '清除素材暫存',
        'confirm_clear_all_data': '確定要清除 IndexedDB 中的所有資料嗎？此操作無法復原！',
        'confirm_clear_chart_cache': '確定要清除所有譜面資料嗎？音效與圖片快取將會保留。',
        'confirm_clear_assets_cache': '確定要清除所有音效與圖片快取資料嗎？譜面資料將會保留。',

        'popup_edit_music_title': '編輯音樂與第一拍 offset',
        'music_edit_first_beat_offset': '第一拍偏移(s):',
        'music_edit_zoom': '縮放:',
        'music_edit_bgm_vol': 'BGM音量:',
        'music_edit_audio_shift': '音訊偏移(s):',
        'music_edit_visual_shift': '視覺偏移',
        'btn_metronome_preview': '節拍器預覽 (從播放頭)',
        'btn_stop_preview': '停止預覽',
        'btn_crop_audio': '裁去播放頭前所有音訊',
        'confirm_crop_audio': '確定要從播放頭處裁切掉前面的音樂嗎？',
        'btn_pad_silence': '在開頭補白 1 拍',
        'btn_apply_shift': '套用音訊偏移',
        'btn_restore_audio': '還原原始音訊',
        'confirm_restore_audio': '確定要放棄本次視窗內的所有裁切/補白修改，還原成剛載入的音樂嗎？',

        'btn_add_bpm': '加入 BPM',
        'tap_bpm_hint': '請連續敲擊「Tap」至少 2 次以計算 BPM，建議 4 次以上會更穩定。',
        'tap_bpm_count': 'Tap 次數',
        'tap_bpm_not_started': '尚未開始敲擊。',
        'tap_bpm_one_more': '再敲一次即可計算 BPM。',
        'tap_bpm_calculating': '目前使用 {count} 個間隔計算 BPM。建議使用 4 次以上敲擊以減少誤差。',

        'popup_load_chart_title': '載入譜面',
        'popup_load_chart_content': '偵測到目前已有編輯內容。\n請選擇要如何處理：',
        'btn_overwrite_project': '覆蓋目前專案',
        'btn_open_as_new_project': '開啟為新專案',
        'popup_search_results_title': '搜尋結果 ({count})',
        'btn_search': '搜尋',
        'popup_fetch_mainote_title': '從 Mainote 抓取譜面',

        'mainote_song_title': '歌曲名稱',
        'mainote_song_title_placeholder': '模糊搜尋...',
        'mainote_level': '難度等級',
        'mainote_difficulty': '難度',
        'mainote_version': '版本',
        'mainote_category': '分類',
        'btn_searching': '搜尋中...',
        'unknown_song': '未知歌曲',
        'mainote_all': '全部',
        'mainote_all_diff': '全部難度',
        'mainote_all_version': '全部版本',
        'mainote_all_category': '全部分類',

        'popup_warning_title': '警告',
        'popup_chart_info_title': '譜面資訊',
        'chart_info_custom_instruction': '自訂指令',
        'chart_info_click_change_image': '點擊更換圖片',
        'chart_info_read_current_track': '從目前 Track 讀取',
        'chart_info_read_audio_metadata': '讀取其他音訊 Metadata',
        'chart_info_title': '標題',
        'chart_info_artist': '作者',
        'chart_info_designer': '譜面設計',
        'chart_info_diff_designer': '難度設計',

        'quick_gen_bpm': 'BPM: ',
        'quick_gen_beat': '節拍分母 (Beat): ',
        'btn_generate': '生成',

        'popup_download_chart_title': '下載譜面套件',
        'btn_download_maidata': '下載 Maidata',
        'btn_download_zip': '打包 ZIP',
        'download_file_name_label': '檔案名稱',
        'download_file_name_placeholder': '輸入檔案名稱',

        'btn_new_project': '新建空白專案',
        'confirm_new_project': '是否要建立新的譜面？這將建立一個新專案。',
        'prompt_project_name': '請輸入專案名稱：',
        'popup_preparing_environment': '正在準備環境...',
        'loading_sfx': '正在載入音效: {key} ({pct}%)',
        'loading_assets': '正在載入素材: {key} ({pct}%)',
        'initializing_project_system': '正在初始化專案系統...',
        'restoring_settings': '正在恢復設定...',
        'restoring_edit_state': '正在恢復上次的編輯狀態...',
        'loading_project_data': '正在載入專案資料...',
        'restoring_editor_content': '還原編輯內容...',
        'loading_complete_rendering': '完成！正在渲染畫面...',

        'pm_no_projects': '尚無任何專案',
        'pm_current': ' （目前）',
        'pm_last_edited': '上次編輯：',
        'btn_open': '開啟',
        'btn_rename': '重新命名',
        'btn_delete': '刪除',
        'prompt_new_project_name': '請輸入新的專案名稱：',
        'alert_cannot_delete_current': '無法刪除目前正在使用的專案。\n請先切換到其他專案後再刪除。',
        'confirm_delete_project': '確定要刪除專案「{name}」嗎？\n此操作無法復原！',

        'init_error_warning': '如果繼續使用可能會遇到不可預期的錯誤，建議先清除資料或重新整理頁面。\n<br>建議可以先清除暫存資料後再嘗試載入，看看是否是因為某筆資料損壞導致的問題。',
        'btn_continue': '繼續',
        'init_error_prefix': '初始化發生錯誤：\n',
        'init_error_suffix': '\n請嘗試重新整理。',

        'rendering_frame_status': '渲染中：第 {current} / {total} 幀',
        'render_done': '完成'
    },
    'en': {
        // static HTML items
        'menu_file': 'File',
        'menu_new': 'New',
        'menu_project_manager': 'Projects',
        'menu_load_folder': 'Load Folder',
        'menu_load_zip': 'Load ZIP',
        'menu_download': 'Download',
        'menu_add_music': 'Add BGM',
        'menu_add_video': 'Add Video',
        'menu_import_from_video': 'Import from Video',
        'menu_read_maidata': 'Load maidata',
        'menu_edit': 'Edit',
        'menu_undo': 'Undo',
        'menu_redo': 'Redo',
        'menu_rotate_cw': 'Rotate CW',
        'menu_rotate_ccw': 'Rotate CCW',
        'menu_rotate_180': 'Rotate 180°',
        'menu_flip_v': 'Flip Vertical',
        'menu_flip_h': 'Flip Horizontal',
        'menu_tools': 'Tools',
        'menu_cursor_to_playhead': 'Cursor to Playhead',
        'menu_playhead_to_cursor': 'Playhead to Cursor',
        'menu_record_video': 'Record Video',
        'menu_edit_music': 'Edit Offset',
        'menu_tap_bpm': 'Tap BPM',
        'menu_quick_generate': 'Quick Gen',
        'menu_fetch_mainote': 'Fetch Mainote',
        'menu_preview_popup': 'Popup Preview',
        'menu_resources': 'Resources',
        'menu_chart_info': 'Chart Info',
        'menu_settings': 'Settings',
        'ui_offset': 'Offset ',
        'ui_difficulty': 'Difficulty ',
        'ui_playback_speed': 'Speed ',
        'ui_display_mode': 'Display ',
        'ui_mode_simai': 'simai Code',
        'ui_mode_visual': 'Track',
        'ui_ready_beat': 'Metronome',
        'editor_placeholder': 'Enter chart data here...',

        // settings configuration keys
        'settings_title': 'Settings',
        'settings_cat_basic': 'Basic',
        'settings_cat_display': 'Display',
        'settings_cat_sound': 'Sound',
        'settings_cat_other': 'Others',
        'settings_speed': ' Tap/Hold Speed',
        'settings_slide_speed': ' Slide Speed',
        'settings_touch_speed': ' Touch Speed',
        'settings_middle_display': 'Center Display',
        'settings_middle_display_off': 'Off',
        'settings_middle_display_combo': 'COMBO',
        'settings_middle_display_score': 'Score',
        'settings_brightness': 'BG Darkness',
        'settings_pink_stars': 'Pink Stars',
        'settings_show_sensor': 'Show Sensors',
        'settings_show_sensor_text': 'Show Sensor Text on Pause',
        'settings_hide_bg_paused': 'Hide BG on Pause',
        'settings_rotate_stars': 'Rotate Stars',
        'settings_vol_global': 'Master Volume',
        'settings_vol_music': 'Music Volume',
        'settings_vol_sfx': 'SFX Volume',
        'settings_vol_individual': 'Individual SFX Volume',
        'settings_no_hold_end_sfx': 'Mute Hold End SFX',
        'settings_autocomplete': 'Autocomplete Brackets',
        'settings_max_slides': 'Max Slides on Screen',
        'settings_debounce_time': 'Update Interval (ms)',
        'settings_show_fps': 'Show FPS overlay',
        'settings_auto_pause': 'Auto Pause on Scroll',
        'settings_global_timeline': 'Show Global Timeline',
        'settings_language': 'Language / 語言',
        'settings_btn_save': 'Save',
        'settings_btn_apply': 'Apply',
        'settings_btn_cancel': 'Cancel',
        'settings_btn_reset': 'Reset Values',

        // SFX names
        'sfx_clock': 'Metronome Tick',
        'sfx_answer': 'Slide Trigger',
        'sfx_judge': 'Tap Hit',
        'sfx_judge_ex': 'EX Tap Hit',
        'sfx_judge_break': 'Break Tap Hit',
        'sfx_judge_break_slide': 'Break Slide Hit',
        'sfx_break': 'Break Hit Sound',
        'sfx_slide': 'Slide Touch Sound',
        'sfx_break_slide_start': 'Break Slide Start',
        'sfx_touch': 'Touch Hit Sound',
        'sfx_hanabi': 'Fireworks sound',

        // Dynamic toasts & Popups
        'toast_saved': 'Saved successfully!',
        'toast_undo': 'Undid chart changes',
        'toast_redo': 'Redid chart changes',
        'toast_import_video_success': 'Imported audio & video successfully',
        'toast_save_video_success': 'Background video saved',
        'toast_save_video_failed': 'Failed to save background video',
        'toast_invalid_number': 'Please ensure all inputs are valid numbers',
        'toast_bpm_set': 'BPM set to: ',
        'toast_speed_set': 'Playback speed set to: ',
        'popup_record_title': 'Video Recording',
        'record_range': 'Range: {start}s - {end}s ({duration}s)',
        'record_resolution': 'Resolution:',
        'record_custom': 'Custom...',
        'record_custom_w': 'Custom Width:',
        'record_custom_h': 'Custom Height:',
        'record_custom_fps': 'Custom FPS:',
        'record_bgm_vol': 'BGM Volume:',
        'record_sfx_vol': 'SFX Volume:',
        'record_include_audio': 'Include Audio:',
        'record_include_sfx': 'Include SFX:',
        'btn_start': 'Start',
        'popup_help_title': 'Help Instructions',
        'btn_ok': 'OK',
        'btn_close': 'Close',
        'btn_reset': 'Reset',

        // Newly added dynamic strings
        'toast_import_music_first': 'Please import audio first',
        'toast_audio_cropped': 'Audio cropped from playback position',
        'toast_audio_padded': 'Silence padded to the beginning of audio',
        'toast_padded_seconds': 'Padded {seconds}s of silence.',
        'toast_crop_too_long': 'Crop length exceeds total audio length.',
        'toast_audio_restored': 'Restored to original audio state',
        'toast_tap_bpm_min': 'Please tap at least 2 times before saving BPM.',
        'toast_bpm_failed': 'BPM calculation failed, please tap again.',
        'toast_supabase_missing': 'Supabase not loaded. Please add CDN in index.html: <script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"></script>',
        'toast_charts_found': 'Found {count} chart(s)',
        'toast_error': 'Error: {message}',
        'toast_no_matching_charts': 'No matching charts found',
        'toast_loaded_song': 'Loaded: {title}',
        'toast_new_project_created': 'Created new project',
        'toast_parse_failed': 'Failed to parse chart, please check if format is correct',
        'toast_invalid_playback_speed': 'Please enter a valid playback speed',
        'toast_speed_reset': 'Reset playback speed',
        'toast_no_audio_file': 'Cannot find audio file',
        'toast_read_tags_success': 'Tags read successfully: {title}',
        'no_title': 'No Title',
        'toast_parsed_from_filename': 'Information parsed from filename',
        'toast_opened_new_project': 'Opened as a new project',
        'toast_loaded_to_current_project': 'Loaded into current project',
        'toast_mediabunny_missing': 'Mediabunny is not loaded, cannot record',
        'toast_switched_to_project': 'Switched to project: {name}',
        'unnamed_project': 'Untitled Project',
        'toast_deleted_project': 'Project deleted',
        'toast_end_time_error': 'End time must be greater than start time',
        'toast_render_complete': 'Frame-by-frame rendering complete, file downloaded',
        'toast_render_failed': 'Rendering failed: ',
        'toast_start_rendering': 'Start frame-by-frame rendering: {count} frames',

        'resource_idb_storage_status': 'IndexedDB Storage Status: ',
        'resource_total_usage': 'Total Usage',
        'btn_clear_cache': 'Clear Cache',
        'popup_clear_cache_title': 'Clear Cache',
        'btn_clear_all_data': 'Clear All Data',
        'btn_clear_chart_cache': 'Clear Chart Cache',
        'btn_clear_assets_cache': 'Clear Assets Cache',
        'confirm_clear_all_data': 'Are you sure you want to clear all data in IndexedDB? This action cannot be undone!',
        'confirm_clear_chart_cache': 'Are you sure you want to clear all chart data? Sound effects and image cache will be preserved.',
        'confirm_clear_assets_cache': 'Are you sure you want to clear all sound effects and image cache? Chart data will be preserved.',

        'popup_edit_music_title': 'Edit Audio & First Beat Offset',
        'music_edit_first_beat_offset': 'First Beat Offset (s):',
        'music_edit_zoom': 'Zoom:',
        'music_edit_bgm_vol': 'BGM Volume:',
        'music_edit_audio_shift': 'Audio Shift (s):',
        'music_edit_visual_shift': 'Visual Offset',
        'btn_metronome_preview': 'Metronome Preview (from Playhead)',
        'btn_stop_preview': 'Stop Preview',
        'btn_crop_audio': 'Crop Audio before Playhead',
        'confirm_crop_audio': 'Are you sure you want to crop the audio before the playhead?',
        'btn_pad_silence': 'Pad 1 Beat Silence at Start',
        'btn_apply_shift': 'Apply Audio Shift',
        'btn_restore_audio': 'Restore Original Audio',
        'confirm_restore_audio': 'Are you sure you want to discard all crops/pads in this session and restore the original audio?',

        'btn_add_bpm': 'Add BPM',
        'tap_bpm_hint': 'Please tap at least 2 times continuously to calculate BPM. 4+ taps recommended.',
        'tap_bpm_count': 'Tap Count',
        'tap_bpm_not_started': 'Tapping not started.',
        'tap_bpm_one_more': 'Tap once more to calculate BPM.',
        'tap_bpm_calculating': 'Currently using {count} intervals to calculate BPM. 4+ taps recommended.',

        'popup_load_chart_title': 'Load Chart',
        'popup_load_chart_content': 'Current project has unsaved edits.\nHow would you like to proceed?',
        'btn_overwrite_project': 'Overwrite Current Project',
        'btn_open_as_new_project': 'Open as New Project',
        'popup_search_results_title': 'Search Results ({count})',
        'btn_search': 'Search',
        'popup_fetch_mainote_title': 'Fetch Charts from Mainote',

        'mainote_song_title': 'Song Title',
        'mainote_song_title_placeholder': 'Fuzzy search...',
        'mainote_level': 'Level',
        'mainote_difficulty': 'Difficulty',
        'mainote_version': 'Version',
        'mainote_category': 'Category',
        'btn_searching': 'Searching...',
        'unknown_song': 'Unknown Song',
        'mainote_all': 'All',
        'mainote_all_diff': 'All Difficulties',
        'mainote_all_version': 'All Versions',
        'mainote_all_category': 'All Categories',

        'popup_warning_title': 'Warning',
        'popup_chart_info_title': 'Chart Info',
        'chart_info_custom_instruction': 'Custom Commands',
        'chart_info_click_change_image': 'Click to change image',
        'chart_info_read_current_track': 'Read from current Track',
        'chart_info_read_audio_metadata': 'Read other Audio Metadata',
        'chart_info_title': 'Title',
        'chart_info_artist': 'Artist',
        'chart_info_designer': 'Chart Designer',
        'chart_info_diff_designer': 'Diff Designer',

        'quick_gen_bpm': 'BPM: ',
        'quick_gen_beat': 'Beat: ',
        'btn_generate': 'Generate',

        'popup_download_chart_title': 'Download Chart Package',
        'btn_download_maidata': 'Download Maidata',
        'btn_download_zip': 'Pack ZIP',
        'download_file_name_label': 'File Name',
        'download_file_name_placeholder': 'Enter file name',

        'btn_new_project': 'New Blank Project',
        'confirm_new_project': 'Do you want to create a new chart? This will create a new project.',
        'prompt_project_name': 'Please enter project name:',
        'popup_preparing_environment': 'Preparing environment...',
        'loading_sfx': 'Loading SFX: {key} ({pct}%)',
        'loading_assets': 'Loading assets: {key} ({pct}%)',
        'initializing_project_system': 'Initializing project system...',
        'restoring_settings': 'Restoring settings...',
        'restoring_edit_state': 'Restoring last edit state...',
        'loading_project_data': 'Loading project data...',
        'restoring_editor_content': 'Restoring editor content...',
        'loading_complete_rendering': 'Complete! Rendering frame...',

        'pm_no_projects': 'No projects found',
        'pm_current': ' (Current)',
        'pm_last_edited': 'Last Edited: ',
        'btn_open': 'Open',
        'btn_rename': 'Rename',
        'btn_delete': 'Delete',
        'prompt_new_project_name': 'Please enter new project name:',
        'alert_cannot_delete_current': 'Cannot delete the current project.\nPlease switch to another project first.',
        'confirm_delete_project': 'Are you sure you want to delete project "{name}"?\nThis action cannot be undone!',

        'init_error_warning': 'If you continue, you might encounter unexpected errors. It is recommended to clear cache or refresh the page.\n<br>Try clearing cached data first and reload to see if any data is corrupted.',
        'btn_continue': 'Continue',
        'init_error_prefix': 'Initialization error:\n',
        'init_error_suffix': '\nPlease try to refresh.',

        'rendering_frame_status': 'Rendering: frame {current} / {total}',
        'render_done': 'Completed'
    },
    'ja': {
        // static HTML items
        'menu_file': 'ファイル',
        'menu_new': '新規作成',
        'menu_project_manager': 'プロジェクト管理',
        'menu_load_folder': 'フォルダ読み込み',
        'menu_load_zip': 'ZIP読み込み',
        'menu_download': 'ダウンロード',
        'menu_add_music': '音楽追加',
        'menu_add_video': '動画追加',
        'menu_import_from_video': '動画からインポート',
        'menu_read_maidata': 'maidata読み込み',
        'menu_edit': '編集',
        'menu_undo': '元に戻す',
        'menu_redo': 'やり直し',
        'menu_rotate_cw': '時計回りに回転',
        'menu_rotate_ccw': '反時計回りに回転',
        'menu_rotate_180': '180度回転',
        'menu_flip_v': '上下反転',
        'menu_flip_h': '左右反転',
        'menu_tools': 'ツール',
        'menu_cursor_to_playhead': 'カーソルを再生ヘッドへ',
        'menu_playhead_to_cursor': '再生ヘッドをカーソルへ',
        'menu_record_video': '動画録画',
        'menu_edit_music': 'オフセット編集',
        'menu_tap_bpm': 'タップ BPM',
        'menu_quick_generate': 'クイック生成',
        'menu_fetch_mainote': 'Mainoteから取得',
        'menu_preview_popup': 'プレビューをポップアップ',
        'menu_resources': 'リソース管理',
        'menu_chart_info': '譜面情報',
        'menu_settings': '設定',
        'ui_offset': 'ズレ ',
        'ui_difficulty': '難易度 ',
        'ui_playback_speed': '速度 ',
        'ui_display_mode': '表示 ',
        'ui_mode_simai': 'simai 構文',
        'ui_mode_visual': 'レーン',
        'ui_ready_beat': 'ガイド音',
        'editor_placeholder': 'ここに譜面データを入力...',

        // settings configuration keys
        'settings_title': '設定',
        'settings_cat_basic': '基本',
        'settings_cat_display': '表示',
        'settings_cat_sound': 'サウンド',
        'settings_cat_other': 'その他',
        'settings_speed': ' Tap/Hold スピード',
        'settings_slide_speed': ' Slide スピード',
        'settings_touch_speed': ' Touch スピード',
        'settings_middle_display': '中央表示',
        'settings_middle_display_off': '非表示',
        'settings_middle_display_combo': 'COMBO',
        'settings_middle_display_score': 'スコア',
        'settings_brightness': '背景の明るさ',
        'settings_pink_stars': 'ピンクの星',
        'settings_show_sensor': 'センサー表示',
        'settings_show_sensor_text': '一時停止時にセンサー名表示',
        'settings_hide_bg_paused': '一時停止時に背景を非表示',
        'settings_rotate_stars': '星の回転',
        'settings_vol_global': 'マスター音量',
        'settings_vol_music': '音楽音量',
        'settings_vol_sfx': '効果音音量',
        'settings_vol_individual': '個別効果音音量',
        'settings_no_hold_end_sfx': 'Hold終点の効果音をミュート',
        'settings_autocomplete': 'エディタの括弧自動補完',
        'settings_max_slides': 'スライドの最大表示数',
        'settings_debounce_time': 'エディタ更新間隔 (ms)',
        'settings_show_fps': 'FPSカウンター表示',
        'settings_auto_pause': 'スクロール時に自動一時停止',
        'settings_global_timeline': 'グローバルタイムライン表示',
        'settings_language': '言語 / Language',
        'settings_btn_save': '保存',
        'settings_btn_apply': '適用',
        'settings_btn_cancel': 'キャンセル',
        'settings_btn_reset': '初期値に戻す',

        // SFX names
        'sfx_clock': 'ガイド音 / Metronome',
        'sfx_answer': 'スライド判定音',
        'sfx_judge': 'タップ判定音',
        'sfx_judge_ex': 'EXタップ判定音',
        'sfx_judge_break': 'Breakタップ判定音',
        'sfx_judge_break_slide': 'Breakスライド判定音',
        'sfx_break': 'Break判定音',
        'sfx_slide': 'スライド操作音',
        'sfx_break_slide_start': 'Breakスライド始点',
        'sfx_touch': 'タッチ判定音',
        'sfx_hanabi': '花火タッチ判定音',

        // Dynamic toasts & Popups
        'toast_saved': '保存しました！',
        'toast_undo': '元に戻しました',
        'toast_redo': 'やり直しました',
        'toast_import_video_success': '動画からBGMと背景動画を読み込みました',
        'toast_save_video_success': '背景動画を保存しました',
        'toast_save_video_failed': '背景動画の保存に失敗しました',
        'toast_invalid_number': '入力が正しい数値であることを確認してください',
        'toast_bpm_set': 'BPMを設定しました：',
        'toast_speed_set': '再生速度を設定しました：',
        'popup_record_title': '動画録画',
        'record_range': '録画範囲: {start}s - {end}s (計 {duration}s)',
        'record_resolution': '解像度:',
        'record_custom': 'カスタム...',
        'record_custom_w': 'カスタム幅:',
        'record_custom_h': 'カスタム高さ:',
        'record_custom_fps': 'カスタムFPS:',
        'record_bgm_vol': 'BGM音量:',
        'record_sfx_vol': 'SFX音量:',
        'record_include_audio': '音声を含む:',
        'record_include_sfx': '打撃音を含む:',
        'btn_start': '開始',
        'popup_help_title': 'ヘルプ',
        'btn_ok': 'OK',
        'btn_close': '閉じる',
        'btn_reset': 'リセット',

        // Newly added dynamic strings
        'toast_import_music_first': '先に音楽を読み込んでください',
        'toast_audio_cropped': '再生位置から音声をトリミングしました',
        'toast_audio_padded': '音声の開始位置に無音を追加しました',
        'toast_padded_seconds': '{seconds}秒の無音を追加しました。',
        'toast_crop_too_long': 'トリミングの長さが総再生時間を超えています。',
        'toast_audio_restored': '元の音声状態に戻しました',
        'toast_tap_bpm_min': 'BPMを保存する前に、少なくとも2回タップしてください。',
        'toast_bpm_failed': 'BPMの計算に失敗しました。もう一度タップしてください。',
        'toast_supabase_missing': 'Supabaseがロードされていません。index.htmlにCDNを追加してください: <script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"></script>',
        'toast_charts_found': '{count}個の譜面が見つかりました',
        'toast_error': 'エラー: {message}',
        'toast_no_matching_charts': '該当する譜面が見つかりません',
        'toast_loaded_song': '読み込み完了: {title}',
        'toast_new_project_created': '新規プロジェクトを作成しました',
        'toast_parse_failed': '譜面の解析に失敗しました。フォーマットが正しいか確認してください',
        'toast_invalid_playback_speed': '有効な再生速度を入力してください',
        'toast_speed_reset': '再生速度をリセットしました',
        'toast_no_audio_file': '音声ファイルが見つかりません',
        'toast_read_tags_success': 'タグを読み込みました: {title}',
        'no_title': '無題',
        'toast_parsed_from_filename': 'ファイル名から情報を解析しました',
        'toast_opened_new_project': '新規プロジェクトとして開きました',
        'toast_loaded_to_current_project': '現在のプロジェクトに読み込みました',
        'toast_mediabunny_missing': 'Mediabunnyがロードされていないため、録画できません',
        'toast_switched_to_project': 'プロジェクトに切り替えました: {name}',
        'unnamed_project': '未命名プロジェクト',
        'toast_deleted_project': 'プロジェクトを削除しました',
        'toast_end_time_error': '終了時間は開始時間より後でなければなりません',
        'toast_render_complete': 'フレーム単位のレンダリングが完了し、ファイルがダウンロードされました',
        'toast_render_failed': 'レンダリング失敗: ',
        'toast_start_rendering': 'フレーム単位のレンダリングを開始します：{count} フレーム',

        'resource_idb_storage_status': 'IndexedDB 保存状態：',
        'resource_total_usage': '総使用量',
        'btn_clear_cache': 'キャッシュクリア',
        'popup_clear_cache_title': 'キャッシュクリア',
        'btn_clear_all_data': 'すべてのデータをクリア',
        'btn_clear_chart_cache': '譜面キャッシュをクリア',
        'btn_clear_assets_cache': '素材キャッシュをクリア',
        'confirm_clear_all_data': 'IndexedDB内のすべてのデータを削除しますか？この操作は取り消せません！',
        'confirm_clear_chart_cache': 'すべての譜面データを削除しますか？効果音と画像のキャッシュは保持されます。',
        'confirm_clear_assets_cache': 'すべての効果音と画像のキャッシュデータを削除しますか？譜面データは保持されます。',

        'popup_edit_music_title': '音声と最初の拍のオフセットを編集',
        'music_edit_first_beat_offset': '最初の拍のオフセット(秒):',
        'music_edit_zoom': 'ズーム:',
        'music_edit_bgm_vol': 'BGM音量:',
        'music_edit_audio_shift': '音声のズレ(秒):',
        'music_edit_visual_shift': '視覚的なズレ',
        'btn_metronome_preview': 'メトロノームプレビュー (再生位置から)',
        'btn_stop_preview': 'プレビュー停止',
        'btn_crop_audio': '再生位置より前の音声をカット',
        'confirm_crop_audio': '再生位置より前の音声を本当にカットしますか？',
        'btn_pad_silence': '開始時に1拍分の無音を追加',
        'btn_apply_shift': '音声のズレを適用',
        'btn_restore_audio': '元の音声に戻す',
        'confirm_restore_audio': 'このセッションでのカット/無音追加をすべて破棄し、元の音声に戻しますか？',

        'btn_add_bpm': 'BPMを追加',
        'tap_bpm_hint': 'BPMを計算するには「Tap」を連続して2回以上タップしてください。4回以上推奨。',
        'tap_bpm_count': 'タップ回数',
        'tap_bpm_not_started': 'タップはまだ開始されていません。',
        'tap_bpm_one_more': 'もう一度タップするとBPMが計算されます。',
        'tap_bpm_calculating': '現在 {count} 個の間隔でBPMを計算中。誤差を減らすため4回以上のタップを推奨します。',

        'popup_load_chart_title': '譜面の読み込み',
        'popup_load_chart_content': '編集中のコンテンツが検出されました。\n処理方法を選択してください：',
        'btn_overwrite_project': '現在のプロジェクトを上書き',
        'btn_open_as_new_project': '新規プロジェクトとして開く',
        'popup_search_results_title': '検索結果 ({count})',
        'btn_search': '検索',
        'popup_fetch_mainote_title': 'Mainoteから譜面を取得',

        'mainote_song_title': '曲名',
        'mainote_song_title_placeholder': 'あいまい検索...',
        'mainote_level': 'レベル',
        'mainote_difficulty': '難易度',
        'mainote_version': 'バージョン',
        'mainote_category': 'カテゴリー',
        'btn_searching': '検索中...',
        'unknown_song': '不明な曲',
        'mainote_all': '全部',
        'mainote_all_diff': '全難易度',
        'mainote_all_version': '全バージョン',
        'mainote_all_category': '全カテゴリー',

        'popup_warning_title': '警告',
        'popup_chart_info_title': '譜面情報',
        'chart_info_custom_instruction': 'カスタムコマンド',
        'chart_info_click_change_image': 'クリックして画像を変更',
        'chart_info_read_current_track': '現在のトラックから読み込む',
        'chart_info_read_audio_metadata': '他のオーディオのメタデータを読み込む',
        'chart_info_title': 'タイトル',
        'chart_info_artist': 'アーティスト',
        'chart_info_designer': '譜面デザイナー',
        'chart_info_diff_designer': '難易度デザイナー',

        'quick_gen_bpm': 'BPM: ',
        'quick_gen_beat': '拍子分母 (Beat): ',
        'btn_generate': '生成',

        'popup_download_chart_title': '譜面パッケージをダウンロード',
        'btn_download_maidata': 'Maidataダウンロード',
        'btn_download_zip': 'ZIPをパッケージ化',
        'download_file_name_label': 'ファイル名',
        'download_file_name_placeholder': 'ファイル名を入力',

        'btn_new_project': '新規空プロジェクト',
        'confirm_new_project': '新しい譜面を作成しますか？これにより新規プロジェクトが作成されます。',
        'prompt_project_name': 'プロジェクト名を入力してください：',
        'popup_preparing_environment': '環境を準備中...',
        'loading_sfx': '効果音読み込み中: {key} ({pct}%)',
        'loading_assets': '素材読み込み中: {key} ({pct}%)',
        'initializing_project_system': 'プロジェクトシステムを初期化中...',
        'restoring_settings': '設定を復元中...',
        'restoring_edit_state': '前回の編集状態を復元中...',
        'loading_project_data': 'プロジェクトデータを読み込み中...',
        'restoring_editor_content': 'エディタの内容を復元中...',
        'loading_complete_rendering': '完了！画面を描画中...',

        'pm_no_projects': 'プロジェクトはまだありません',
        'pm_current': ' （現在）',
        'pm_last_edited': '最終編集：',
        'btn_open': '開く',
        'btn_rename': '名前変更',
        'btn_delete': '削除',
        'prompt_new_project_name': '新しいプロジェクト名を入力してください：',
        'alert_cannot_delete_current': '現在使用中のプロジェクトは削除できません。\n別のプロジェクトに切り替えてから削除してください。',
        'confirm_delete_project': 'プロジェクト「{name}」を削除しますか？\nこの操作は取り消せません！',

        'init_error_warning': 'このまま使用すると予期しないエラーが発生する可能性があります。データをクリアするか、ページを再読み込みすることをお勧めします。\n<br>特定のデータ破損が原因か確認するため、キャッシュをクリアして再試行することをお勧めします。',
        'btn_continue': '続行',
        'init_error_prefix': '初期化中にエラーが発生しました：\n',
        'init_error_suffix': '\n再読み込みしてください。',

        'rendering_frame_status': 'レンダリング中：{current} / {total} フレーム',
        'render_done': '完了'
    }
};

export function getSystemLang(configLang) {
    if (configLang && configLang !== 'auto') return configLang;
    const navLang = navigator.language || navigator.userLanguage || 'zh-TW';
    if (navLang.startsWith('ja')) return 'ja';
    if (navLang.startsWith('en')) return 'en';
    return 'zh-TW';
}

export function t(key, customLang = null) {
    const activeLang = customLang || (window.settings && window.settings.language) || 'auto';
    const lang = getSystemLang(activeLang);
    return translations[lang]?.[key] || translations['zh-TW']?.[key] || key;
}

export function applyTranslations(lang = null) {
    const activeLang = lang || (window.settings && window.settings.language) || 'auto';
    const finalLang = getSystemLang(activeLang);

    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        const translation = translations[finalLang]?.[key] || translations['zh-TW']?.[key];
        if (translation) {
            // Find text node directly or replace content if no elements
            let textNode = Array.from(el.childNodes).find(node => node.nodeType === Node.TEXT_NODE);
            if (textNode) {
                textNode.nodeValue = translation;
            } else {
                if (el.children.length === 0) {
                    el.textContent = translation;
                } else {
                    // if it has children and no text node, insert as first child
                    const newText = document.createTextNode(translation);
                    el.insertBefore(newText, el.firstChild);
                }
            }
        }
    });

    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        const translation = translations[finalLang]?.[key] || translations['zh-TW']?.[key];
        if (translation) {
            el.placeholder = translation;
        }
    });
}
